service: class-time
app: classtime
org: tachyon
frameworkVersion: '1'
provider:
  name: aws
  runtime: nodejs12.x

functions:
  schedule:
    handler: functions/handler.schedule
    events:
      - http:
          path: schedule
          method: get
          cors: true


plugins:
  - serverless-s3-sync
  - serverless-domain-manager

resources:
  Resources:
    AssetsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: www.mooneyclassschedule.com
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
    AssetsBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: AssetsBucket
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObjecdt
              Effect: Allow
              Principal: "*"
              Action:
                - s3:GetObject
              Resource:
                Fn::Join: [ "", [ "arn:aws:s3:::", { "Ref": "AssetsBucket" }, "/*" ] ]

custom:
  customDomain:
    domainName: api.mooneyclassschedule.com
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
  s3Sync:
    - bucketName: www.mooneyclassschedule.com
      localDir: public/

